apiVersion: v2
dependencies:
  - condition: firefly-db.enabled
    name: firefly-db
    repository: https://github.com/kvdomingo/charts
    version: 0.2.0
  - condition: firefly-iii.enabled
    name: firefly-iii
    repository: https://github.com/kvdomingo/charts
    version: 1.5.0
  - condition: importer.enabled
    name: importer
    repository: https://github.com/kvdomingo/charts
    version: 1.4.0
  - name: redis
    version: 18.6.2
    repository: https://charts.bitnami.com/bitnami
description: Installs Firefly III stack (db, app, importer)
home: https://github.com/firefly-iii/kubernetes
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
maintainers:
  - email: hello@kvd.studio
    name: kvdomingo
name: firefly-iii-stack
sources:
  - https://github.com/firefly-iii/kubernetes
type: application
version: 0.8.0
